describe ("automationexercise test cases", ()=>{
  it("register user",()=>{

    cy.visit( 'http://automationexercise.com')
cy.get('.shop-menu>.nav>:nth-child(4) > ').click()
cy.get('.signup-form > h2').should('have.text','New User Signup!')
cy.get('[data-qa="signup-name"]').type('anano')
cy.get('[data-qa="signup-email"]').type('achezhia172@gmail.com')
cy.get('[data-qa="signup-button"]').click()
cy.get(':nth-child(1) > b').should('be.visible')
cy.get('#id_gender1').click()
cy.get('[data-qa="password"]').type('anano123')
cy.get('[data-qa="days"]').select(12)
cy.get('[data-qa="months"]').select('October')
cy.get('[data-qa="years"]').select("2003")
cy.get('#newsletter').click()
cy.get('#optin').click()
cy.get('[data-qa="first_name"]').type('anano')
cy.get('[data-qa="last_name"]').type('chezhia')
cy.get('[data-qa="company"]').type('smartacademy')
cy.get('[data-qa="address"]').type('tamarashvili 13')
cy.get('[data-qa="address2"]').type('chavchavadze 7')
cy.get('[data-qa="country"]').select('United States')
cy.get('[data-qa="state"]').type('New York')
cy.get('[data-qa="city"]').type('New York')
cy.get('[data-qa="zipcode"]').type(11801)
cy.get('[data-qa="mobile_number"]').type(557118662)
cy.get('[data-qa="create-account"]').click()
cy.get('b').should('be.visible')
cy.get('[data-qa="continue-button"]').click()
cy.get(':nth-child(10) > a').should('be.visible')
cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
cy.get('b').should('be.visible')
cy.get('[data-qa="continue-button"]').click()

  })  
})